[book]
title = "Tensorflow - Help Protect the Great Barrier Reef"
authors = ["Rishabh"]
description = "Detect crown-of-thorns starfish in underwater image data"
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/anonymousr007/kaggle-reef"
git-repository-icon = "fa-github"
mathjax-support = true